# Generated by Django 5.0.1 on 2024-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_small', models.ImageField(upload_to='media', verbose_name='Small Image')),
                ('img_large', models.ImageField(upload_to='media', verbose_name='Large Image')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
