# Generated by Django 5.0.1 on 2024-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media', verbose_name='First Image')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Second Image')),
                ('img3', models.ImageField(upload_to='media', verbose_name='Third Image')),
                ('img4', models.ImageField(upload_to='media', verbose_name='Forth Image')),
            ],
            options={
                'verbose_name': 'BackGround Image',
                'verbose_name_plural': 'BackGround Images',
            },
        ),
    ]
